### ISSUE TITLE
Support for a "no results" div

### ISSUE THREAD

**Issue by jasonsims** [swiftype/swiftype-autocomplete-jquery#11]
Is it possible to update the search div with "no results" if nothing is found? Today the behavior shows nothing at all if no results are returned. It looks like the config supports

```
noResultsClass: 'noResults'
noResultsMessage: undefined
```

however, nothing really seems to be done with this items at the moment.

**Comment by tommotaylor** [comment]
Has anyone got an implementation to follow here? I can configure `noResultsClass` and `noResultsMessage` but like above, nothing happens.

**Comment by davishmcclurg** [comment]
@tommotaylor support for `noResultsClass` and `noResultsMessage` was added back here: https://github.com/swiftype/swiftype-autocomplete-jquery/pull/25

Give it a try and let me know if you have any issues.
