### ISSUE TITLE
Support custom function on Enter keydown

### ISSUE THREAD

**Issue by jgillman** [swiftype/swiftype-autocomplete-jquery#12]
When typing in the autocomplete input field, users (in my experience) expect to be able to hit Enter and get taken to a "full results" page. I would like to add an optional `onEnterKeydownFunction` to support this.

The function would only be triggered if the user hasn't used the arrow or mouse keys to select an item in the autocomplete results list.

**Comment by Gediminas19** [comment]
I am curious if arrow keys + enter are still able to trigger `onComplete`. I am having a problem where arrow keys + enter ends up calling `onSubmit`, and I would like to know if it's because of a change to autocomplete.

**Comment by JasonStoltz** [comment]
Hey @Gediminas19, this code hasn't been changed since 2019, so I don't think it would be caused by a change to autocomplete.

**Comment by JasonStoltz** [comment]
If you can reproduce this in a https://codesandbox.io/ or something I am happy to help you debug.
