### ISSUE TITLE
Customizing the Display

### ISSUE THREAD

**Issue by johngibbons** [swiftype/swiftype-autocomplete-jquery#18]
I'm trying to follow along with the "Customizing the Display" portion of the readme and I'm running into an issue.  I'm using the Wordpress plugin and am trying to overwrite the renderFunction method of the swiftypeConfig object.  I'm getting the console error: "Uncaught TypeError: Cannot read property 'title' of undefined" so I know that the script is injecting into wp_head properly.

Here is my code:

    <?php 
    function swiftype_javascript_config() {
    ?>
    <script type="text/javascript">
     var customRenderFunction = function(document_type, item) {
        var out = '<p class="title">' + item['title'] + '</p>';
        return out.concat('<p class="post-type">' + item['object_type'] + '</p>');
     };

     var swiftypeConfig = {
      renderFunction: customRenderFunction(),
      fetchFields: {'posts': ['title', 'object_type']},
      searchFields: {'posts': ['title', 'tags', 'author', 'body', 'excerpt', 'project_description', 'flex_description', 'troper_job', 'troper_bio']}
    };
    </script>
    <?php
    }

    add_action('wp_head', 'swiftype_javascript_config');
    ?>

Thanks for your help.

**Comment by qhoxie** [comment]
Hi John,

Though I haven't run the code, it looks like the issue is how you are passing the custom function into the configuration.  You need to pass it as "customRenderFunction" without the parentheses on the end.  For reference, when the parentheses are present, it is actually executing the function with both arguments undefined.  This is why you see that error.

Hope that helps.

Best,
Quin

**Comment by johngibbons** [comment]
Quin,

Thanks for the quick reply.  Removing the parentheses got rid of the console error, but I'm still seeing not seeing anything changing with the autocomplete formatting.  I'm just getting the standard autocomplete dropdown with the paragraph tags with the title class.  I've tried putting a console.log within the customRenderFunction and am not seeing anything so it seems like it's not being called by Swiftype.  Let me know if you have any suggestions.

Thanks,
John

**Comment by anthias** [comment]
Hi John,
This pull request adds the functionality you were expecting: https://github.com/swiftype/swiftype-wordpress/pull/25

It's available in version 1.1.45 of the Swiftype Wordpress plugin.

Best,
          jeff
