### ISSUE TITLE
Follow-up to closed Issue #18

### ISSUE THREAD

**Issue by dan-at-unkubed** [swiftype/swiftype-autocomplete-jquery#20]
I'm having what seems to be the same issue mentioned by johngibbons in closed Issue #18.  In that discussion, you mentioned that the functionality he was expecting was present in version 1.1.45 of the plugin, but I'm not seeing that my implementation is working.  I'm currently using version 1.1.45 of the plugin with Wordpress 4.3.1.  The plugin seems to be working great, other than the fact that I can't figure out how to customize anything yet.  :)

I tried affecting the customization as per the current README documentation, which for my case is (this code is within a custom scripts file for my site, which is loaded in the footer, and references a search input field that is currently using the swiftype functionality):

```
var customSwiftypeRender = function(document_type, item) {
    return '<p class="title">HELLO::' + item['title'] + '</p>';
};
jQuery('#search-from-header .s').swiftype({ 
    'renderFunction': customSwiftypeRender,
    'engineKey': swiftypeParams.engineKey
});
```

but regardless of whether I put that into a document.ready or window.load wrapper, that only resulted in the following js error:

```
Uncaught TypeError: jQuery(...).swiftype is not a function
```

Then I found johngibbons's closed issue and tried to use that approach (which is not reflected in the current README documentation, but looks to have some merit as per searching through the swiftype script that is loading on my site and finding the global object referenced in Issue 18) simply via:

```
var customSwiftypeRender = function(document_type, item) {
    console.log('Hello!');
    return '<p class="title">HELLO::' + item['title'] + '</p>';
};
var swiftypeConfig= { 
    'renderFunction': customSwiftypeRender,
    'engineKey': swiftypeParams.engineKey
};
```

and that avoids the error, but I'm not seeing any difference in the autocomplete results.  There's no indication as to what the causal problem with johngibbons's reported issue was, so I'm not sure how to solve the problem now, as I've done everything that I can see to try at this point with what has been presented in this gitHub repo.

Any help or direction would be appreciated.  Thanks.

Dan

**Comment by JasonStoltz** [comment]
@dan-at-unkubed I am closing this issue since it is 3 years old.

For posterity, what you have in your first example is correct. That error message would indicate to me that your code, however, is executing before `jquery.swiftype.autocomplete.js` is loaded.
