### ISSUE TITLE
Queries with special characters cause undefined suggestions

### ISSUE THREAD

**Issue by robb3rt** [swiftype/swiftype-autocomplete-jquery#40]
The JQuery plugin is using the [`/api/v1/public/engines/suggest.json`](https://swiftype.com/documentation/site-search/autocomplete) API endpoint under the hood and looking at the returned results and their highlights for the title. It is using that to populate the autocomplete list in the interface. There are some issues that can occur when the API call returns matches for the search query, but no highlights are returned:
![Screenshot 2019-06-13 at 16 54 11](https://user-images.githubusercontent.com/12517715/59443236-e3d1dc80-8dfb-11e9-93e6-5d7b08b5d09c.png)

This can happen when special characters are used in the search query, for example `a-`, would become prefix matched against documents in the engine and most likely return results in the search query.

The plugin would in this case show a list of `undefined` documents:
![Screenshot 2019-06-13 at 16 31 06](https://user-images.githubusercontent.com/12517715/59441322-acadfc00-8df8-11e9-8eab-7c61b81e84c9.png)

The reason for this issue is because there is no exact match for `a-` in these found matches, so there is no available highlight, which this plugin needs to show suggestions in the interface. The suggest.json API does return the title of the matches, so you could use that to display the results of these searches if no highlights are returned.

**Comment by robb3rt** [comment]
this should be resolved by adjusting the custom renderfunction

**Comment by JasonStoltz** [comment]
Thank you for the update @robb3rt.
