### ISSUE TITLE
Option to open in a new window

### ISSUE THREAD

**Issue by imrane** [swiftype/swiftype-autocomplete-jquery#7]
Are we able to open one of the autocomplete options in a new window?

**Comment by blink188** [comment]
This is exactly what I wish to do, But I don't understand from the explanation above how to do it...
I am gonna copy your function:
var defaultOnComplete = function(item, prefix) {
   window.location = item['url'];
 };

And paste it somewhere on my HTML?

and then where fo I put the:

$("#selector").swiftype({
  // ... other configuration options ...
  onComplete: yourFunction
});

Can you explain in more detail?

Thanks!

**Comment by dannyid** [comment]
@look, So the custom (or default) onComplete function is what executes when the autocomplete item is clicked? Are all the other options for those autocomplete results set in the customRenderFunction?

**Comment by look** [comment]
@dannyid yes, the onComplete function is called when an item is clicked.

There's two render functions you might be interested in: `renderFunction` renders an individual item. `resultRenderFunction` renders the whole autocomplete results -- by default, it calls the configured `renderFunction` once for each result and appends them into a container.

You can see some examples here:

https://github.com/swiftype/swiftype-autocomplete-jquery/blob/master/custom.html
https://github.com/swiftype/swiftype-autocomplete-jquery/blob/master/custom_dropdown.html
https://github.com/swiftype/swiftype-api-example/blob/master/search/index.html
